<a href="https://colab.research.google.com/github/sreebalajisree/python_handson/blob/main/extractedText_deviceinfo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
!pip install easyocr

In [7]:
!pip install opencv-python-headless==4.1.2.30

     |████████████████████████████████| 21.8 MB 2.4 MB/s 
  Attempting uninstall: opencv-python-headless
    Found existing installation: opencv-python-headless 4.5.5.64
    Uninstalling opencv-python-headless-4.5.5.64:
      Successfully uninstalled opencv-python-headless-4.5.5.64


In [8]:
import easyocr
import cv2

In [9]:
# Load the google drive
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [12]:
reader = easyocr.Reader(['en'])
output = reader.readtext("/content/device_info1.jpg")
output

CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.


[([[25, 13], [223, 13], [223, 55], [25, 55]], 'SMAREDTV', 0.5913040883835136),
 ([[973, 17], [1173, 17], [1173, 55], [973, 55]],
  'XOverABR',
  0.9995070422733559),
 ([[1794, 20], [1822, 20], [1822, 46], [1794, 46]], '0', 0.9771506309887315),
 ([[1830, 20], [1858, 20], [1858, 46], [1830, 46]], '0', 0.5641889117560481),
 ([[12, 94], [36, 94], [36, 118], [12, 118]], '3', 0.934906657989373),
 ([[53, 95], [159, 95], [159, 115], [53, 115]],
  'Device Status',
  0.8130415432182342),
 ([[272, 92], [478, 92], [478, 118], [272, 118]],
  'Device Information',
  0.910271829568761),
 ([[276, 146], [392, 146], [392, 166], [276, 166]],
  'Personalization',
  0.999988826908191),
 ([[819, 149], [881, 149], [881, 167], [819, 167]],
  'Network',
  0.9999802199681402),
 ([[52, 158], [184, 158], [184, 182], [52, 182]],
  'Configure Device',
  0.9991724209596137),
 ([[291, 179], [339, 179], [339, 193], [291, 193]],
  'SERIAL',
  0.9763052406533913),
 ([[833, 179], [869, 179], [869, 193], [833, 193]],
  'D

In [42]:
import numpy as np
arr = np.array(output)
x,y,z = arr.T

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


In [43]:
print(x,y,z)

[list([[25, 13], [223, 13], [223, 55], [25, 55]])
 list([[973, 17], [1173, 17], [1173, 55], [973, 55]])
 list([[1794, 20], [1822, 20], [1822, 46], [1794, 46]])
 list([[1830, 20], [1858, 20], [1858, 46], [1830, 46]])
 list([[12, 94], [36, 94], [36, 118], [12, 118]])
 list([[53, 95], [159, 95], [159, 115], [53, 115]])
 list([[272, 92], [478, 92], [478, 118], [272, 118]])
 list([[276, 146], [392, 146], [392, 166], [276, 166]])
 list([[819, 149], [881, 149], [881, 167], [819, 167]])
 list([[52, 158], [184, 158], [184, 182], [52, 182]])
 list([[291, 179], [339, 179], [339, 193], [291, 193]])
 list([[833, 179], [869, 179], [869, 193], [833, 193]])
 list([[291, 203], [423, 203], [423, 223], [291, 223]])
 list([[831, 203], [867, 203], [867, 223], [831, 223]])
 list([[53, 223], [141, 223], [141, 243], [53, 243]])
 list([[293, 251], [329, 251], [329, 265], [293, 265]])
 list([[291, 275], [423, 275], [423, 295], [291, 295]])
 list([[831, 275], [931, 275], [931, 295], [831, 295]])
 list([[52, 286]

In [61]:
i  = 0
for wrd in y:
  print(i)
  print(wrd)
  concat = wrd
  file =  open("extractedText.txt", "a")
  file.write("\n")
  file.write(concat)
  i += 1
  file.close


0
SMAREDTV
1
XOverABR
2
0
3
0
4
3
5
Device Status
6
Device Information
7
Personalization
8
Network
9
Configure Device
10
SERIAL
11
DHCP
12
30100000092096
13
YES
14
Device Info
15
CSSN
16
30100000092096
17
10.27.15.166
18
Device Update
19
MAC
20
MASK
21
Logs
22
00.20-1BBA:O2.DB
23
255.255.255.0
24
GATEWAY
25
About
26
10.27.15.255
27
Software Version
28
XOVER
29
1,.0.0
30
XOVER SERVER
31
0.1.0
32
NANOCDN RR
33
v2.4.2-trunk-4286
34
NANOCDN CORE
35
v2.4.2-trunk@4286, BkStbA 2.2.0 - API 6.7
36
SVN 775
37
KERNEL
38
4.19.127+


In [91]:
i = 0
for coor in x:
  print(i)
  print(coor)
  concat = coor
  file =  open("extractedCoordinates.txt", "a")
  file.write("\n")
  file.write(str(concat))
  i += 1
  file.close

ValueError: ignored

In [68]:
import pandas as pd
df = pd.read_csv("/content/extractedText.txt")
df.head()

Text
0  SMAREDTV
1  XOverABR
2         0
3         0
4         3

In [95]:
df1 = pd.read_csv("/content/extractedcoordinates.txt")
df1.head()

co-ordinates
[[25    13]  [223   13]  [223   55]   [25           55]]
[[973   17]  [1173  17]  [1173  55]   [973          55]]
[[1794  20]  [1822  20]  [1822  46]   [1794         46]]
[[1830  20]  [1858  20]  [1858  46]   [1830         46]]
[[12    94]  [36    94]  [36    118]  [12          118]]

In [87]:
df1.to_csv('extractedCoordinates.csv')

In [96]:
frames = [df, df1]
new_df = df1.append(df, ignore_index=True)
new_df.head()

co-ordinates Text
0         55]]  NaN
1         55]]  NaN
2         46]]  NaN
3         46]]  NaN
4        118]]  NaN

In [93]:
new_df

co-ordinates  \
([[25,, 13],, [223,, 13],, [223,, 55],, [25,)              55]]   
([[973,, 17],, [1173,, 17],, [1173,, 55],, [973,)          55]]   
([[1794,, 20],, [1822,, 20],, [1822,, 46],, [17...         46]]   
([[1830,, 20],, [1858,, 20],, [1858,, 46],, [18...         46]]   
([[12,, 94],, [36,, 94],, [36,, 118],, [12,)              118]]   
...                                                         ...   
34                                                          NaN   
35                                                          NaN   
36                                                          NaN   
37                                                          NaN   
38                                                          NaN   

                                                                                        Text  
([[25,, 13],, [223,, 13],, [223,, 55],, [25,)                                            NaN  
([[973,, 17],, [1173,, 17],, [1173,, 55],, [973,)                                        NaN  
([[1794,, 20],, [1822,, 20],, [1822,, 46],, [17...                                       NaN  
([[1830,, 20],, [1858,, 20],, [1858,, 46],, [18...                                       NaN  
([[12,, 94],, [36,, 94],, [36,, 118],, [12,)                                             NaN  
...                                                                                      ...  
34                                                                              NANOCDN CORE  
35                                                  v2.4.2-trunk@4286-BkStbA 2.2.0 - API 6.7  
36                                                                                   SVN 775  
37                                                                                    KERNEL  
38                                                                                 4.19.127+  

[77 rows x 2 columns]

In [97]:
new_df.to_csv('dummy.csv')

In [98]:
df.to_csv('extractedText.csv')